name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: 17

      - name: Update version
        run: mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find JAR
        id: find_jar # find '*-jar-with-dependencies.jar'
        run: echo ::set-output name=stdout::$(find . -name '*-jar-with-dependencies.jar')

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.find_jar.outputs.stdout }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}